project2/config/routes.rb
Rails.application.routes.draw do

  get '/performer_sessions/new', to: "performer_sessions#new", as: "performer_login"

  post '/performer_sessions', to: "performer_sessions#create"

  delete '/performer_sessions', to: "performer_sessions#destroy"

  # Categories
  resources :categories

  root to: "clients#index"

  ### CLIENTS ###


  get "/clients", to: "clients#index", as: "home"

  get "/clients/new", to: "clients#new", as: "new_client"

  post "/clients", to: "clients#create"

  get "/clients/:id/edit", to: "clients#edit", as: "edit_client"

  get "/clients/:id", to: "clients#show", as: "client_path"

## UPDATE ROUTE 
  # put "/clients/:id", to: "clients#update"

  patch "/clients/:id", to: "clients#update", as:"update_client"

  delete "/clients/:id", to: "clients#destroy"


  ### PERFORMERS ###

  get "/performers", to: "performers#index"

  get "/performers/new", to: "performers#new", as: "new_performer"

  post "/performers", to: "performers#create"

  get "/performers/:id", to: "performers#show", as: 'performer'

  get "/performers/:id/edit", to: "performers#edit", as: "edit_performer"

  patch "/performers/:id", to: "performers#update"

  delete "/performers/:id", to: "performers#destroy"

  ### CLIENT SESSIONS ###

  get "/sessions/new", to: "sessions#new", as: 'login'

  post "/sessions", to: "sessions#create", as: 'login_user'

  delete "/sessions", to: "sessions#destroy", as: "logout"

end

project2/app/models/client.rb
class Client < ActiveRecord::Base

	has_secure_password
	has_many :reviews

	validates :email, :firstname, :lastname, presence: true
	validates :email, uniqueness: true
	validates :password, presence: true, length: { minimum: 6 } 


	def self.confirm(params)
	    @client = Client.find_by({email: params[:email]})
	    @client.try(:authenticate, params[:password])
	end


end

project2/app/models/performer.rb
class Performer < ActiveRecord::Base

	has_secure_password

	### I suggest we consider changing Performer model - to just include Performer / Group Name ###
	validates :performer_name, :email, :password_digest, :city, :hourly_rate, :description, presence: true
	# performers must have unique names and email addresses
	validates_uniqueness_of :performer_name, :email
	validates :password, length: { minimum: 6 }
	validates :description, length: { minimum: 30, maximum: 500 }

	belongs_to :category

	has_attached_file :avatar, styles: { thumb: "100x100!" }, :default_style => :thumb, default_url: "/images/:style/missing.png"
  	validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

  	has_attached_file :image1, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  	validates_attachment_content_type :image1, content_type: /\Aimage\/.*\Z/

  	has_attached_file :image2, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  	validates_attachment_content_type :image2, content_type: /\Aimage\/.*\Z/

  	has_attached_file :image3, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  	validates_attachment_content_type :image3, content_type: /\Aimage\/.*\Z/

	def self.confirm(params)
	    @performer = Performer.find_by({email: params[:email]})
	    @performer.try(:authenticate, params[:password])
	end


end

project2/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include SessionsHelper
  include PerformerSessionsHelper
  

end

project2/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  
  def index
  	redirect_to "/"
  end

  def show
  	@category = Category.find_by({id: params[:id]})
  	@performer = Performer.order(created_at: :desc).where(["category_id = #{@category.id}"])
  end

end

project2/app/controllers/clients_controller.rb
class ClientsController < ApplicationController

def index
    @clients = Client.all
    render :index
  end

def show
  id = params[:id]
  @client = Client.find(params[:id])
  render :show
  end

  def new
    @client = Client.new
    render :new
  end

  def create
    client_params = params.require(:client).permit(:firstname, :lastname, :email, :password)
    @client = Client.create(client_params)
    if @client.save
      flash[:success] = "Welcome!"
      redirect_to("/clients/#{@client.id}")
    else
      flash[:danger] = "It failed!"
      render 'new'
    end
  end



  def edit
    @client = Client.find(params[:id])
    render :edit
  end

  def update
      client_id = params[:id]
      client = Client.find(client_id)
      # get updated data
      updated_attributes = params.require(:client).permit(:firstname, :lastname)
      # update the client
      client.update_attributes(updated_attributes)
      client.save(validate: false)
      #redirect to show
      redirect_to "/clients/#{client.id}"  # <-- go to show
    end

 def destroy
  end

  
end
private

  def client_params
    params.require(:client).permit(:firstname, :lastname, :email, :password)
  end
  

project2/app/controllers/performer_sessions_controller.rb
class PerformerSessionsController < ApplicationController
  def new
  	@performer = Performer.new
  	render :new
  end

  def create
  	@performer = Performer.confirm(params[:performer])
  	if @performer
  		login(@performer)
      redirect_to performer_path(@performer)
  	else
  		redirect_to performer_login_path
  	end
  end

  def destroy
  	session[:performer_id] = nil
  	redirect_to root_path
  end
end

project2/app/controllers/performers_controller.rb
class PerformersController < ApplicationController

def index
		@performers = Performer.all
	end

	def new
		@performer = Performer.new
	end

	def create
		@performer = Performer.create(performer_params)
	    if @performer.save
	      flash[:success] = "Welcome!"
	      redirect_to("/performers/#{@performers.id}")
	    else
	      flash[:danger] = "It failed!"
	      render 'new'
	    end
	end

	def show
		@performer = Performer.find_by_id(params[:id])
		@category = Category.find_by_id(@performer.category)
		@video1 = @performer.video1

	end

	def edit
		@performer = Performer.find(params[:id])
    		if @performer.id == current_performer.id
        		render :edit
    		else
        		redirect_to root_path
    		end
  	end

	def update
    	@performer = Performer.find(params[:id])    
      		if @performer.update(performer_params)
         		redirect_to performer_path(@performer)
      		else
        		render :edit
      		end
  	end

	def destroy
	end

	private

	def performer_params
		params.require(:performer).permit(:performer_name, :email, :password, :city, :category_id, :performer_subcategory, :hourly_rate, :description, :avatar, :image1, :image2, :image3, :video1, :video2, :video3)
	end


end

project2/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  	@client = Client.new
  end

  def create
    @client = Client.confirm(params[:client])
    if @client
      login(@client)
      redirect_to "/clients/#{@client.id}"
    else
      flash[:danger] = "It failed!"
      redirect_to "/sessions/new"
    end
  end

  def destroy
    # logout
    session[:client_id] = nil
    redirect_to root_path
  end
end

project2/app/helpers/application_helper.rb
module ApplicationHelper
	include SessionsHelper
end

project2/app/helpers/categories_helper.rb
module CategoriesHelper
end

project2/app/helpers/performer_sessions_helper.rb
module PerformerSessionsHelper

	def login(performer)     
		session[:performer_id] = performer.id     
		@current_performer = performer   
	end    

	def current_performer     
		@current_performer ||= ( session[:performer_id].nil? ? false : Performer.find(session[:performer_id]) )   
	end    

	def logged_in?     
		if current_performer == nil       
		   redirect_to "/performer_sessions/new"     
		end   
	end    

	def logout     
		@current_performer = session[:performer_id] = nil   
	end


end

project2/app/helpers/performers_helper.rb
module PerformersHelper
	def embed(youtube_url)
		youtube_id = youtube_url.split("=").last
		content_tag(:iframe, nil, src: "//www.youtube.com/embed/#{youtube_id}")
	end
end

project2/app/helpers/sessions_helper.rb
module SessionsHelper
	def login(client)
    session[:client_id] = client.id
    @current_client = client
  end

  def logged_in?
    if @current_client == nil
      redirect_to "/sessions/new"
    end
  end

  def destroy
    @current_client = session[:client_id] = nil
  end

  private
  def current_client 
    @current_client ||= Client.find(session[:client_id]) if session[:client_id]
  end
end

project2/app/views/categories/index.html.erb
<h1>Categories#index</h1>
<p>Find me in app/views/categories/index.html.erb</p>

project2/app/views/categories/show.html.erb
<div class="container">
	<h1>Browse all <%= @category.category %>s! </h1>

	<% @performer.each do |performer| %>
		<div class="jumbotron">
			<div>
				<%= image_tag performer.avatar.url(:thumb) %>
			</div>
			<div>
				<%= performer.performer_name %>
				<br>
				<%= performer.description %>
				<br>
				<%= performer.performer_subcategory %>
			</div>
			<div>
				<%= performer.hourly_rate %>
			</div>
			<div class="btn btn-primary" role="button">
				<%= link_to "View Full Profile", performer_path(performer.id) %>
			</div>
		</div>
	<% end %>	

</div>

project2/app/views/clients/edit.html.erb
<h1>Edit Client</h1>

  <div class="form-group">
    <%= form_for @client, url: update_client_path, method: :patch do |f| %>
    <p><%= f.text_field :firstname, placeholder: 'First Name', required: true %></p>
    <p><%= f.text_field :lastname, placeholder: 'Last Name', required: true %></p>
  </div>
  <%= f.submit "edit" %>
  <% end %>

project2/app/views/clients/index.html.erb
<div class="jumbotron">
  <div class="container">
  <h1>Find a performer near you</h1>
  <p>The best local performers.</p>
  <button type="button" class="btn btn-default btn-lg btn-block"><%= link_to "Search All Perfomers", performers_path %></button>
  </div>
</div>

<div class="container">
<!-- row of columns -->
  <div class="col-md-4">
    <h3>Hire performers.</h3>
    <div><img class="perf" src="http://i.cdn.talentegg.ca/incubator/wp-content/uploads/bourke3.jpg">
    </div>
    <p>Make it memorable</p>
    <button type="button" class="btn btn-sm btn-info"><%= link_to "Musical Acts", "/categories/1" %></button>   
  </div>
<!-- row of columns -->
<div class="col-md-4">
    <h3>Do you love magic?</h3>
    <div><img class="perf" src="http://www.neurosciencemarketing.com/blog/wp-content/uploads/2010/11/magician-cards.jpg">
    </div>
      <p>Browse magicians and clowns near you.</p>
      
      <button type="button" class="btn btn-sm btn-info"><%= link_to "Comedy Acts", "/categories/2" %></button> 
      </div>
    <!-- row of columns -->
<div class="col-md-4">
    <h3>Looking for a laugh?</h3>
    <div><img class="perf" src="http://nickshell1983.files.wordpress.com/2011/01/stand-up-comedy-mic.jpg">
    </div>
      <p>The funniest comics are at your event.</p>
      <button type="button" class="btn btn-sm btn-info"><%= link_to "Circus Acts", "/categories/3" %></button> 
    </div>
</div>
<hr>
<footer id="footer" class="container-brand-dar footer-surround footer-container">
    <footer class="page-container-responsive">
      <div class="text-center page-container-responsive">
        <div class="row row-condensed">
          <div class="col-md-2 cold-md-offset-1 hide-sm">
            
          </div>
          <div class="col-md-2 cold-md-offset-1 hide-sm">
            
          </div>
          <div class="col-md-2 hide-sm">
            <h2 class="h5">Discover</h2>
            <ul class="list-layout">
              <li>
                <a href="#">Trust and Safety</a>
              </li>
              <li>
                <a href="#">Tell your friends</a>
              </li>
            </ul>
          </div>
          <div class="col-md-2 hide-sm">
            <h2 class="h5">Our Team</h2>
            <ul class="list-layout">
              <li>
                <a href="#">About</a>
              </li>
              <li>
                <a href="#">Contact</a>
              </li>
            </ul>
          </div>
  </footer>

project2/app/views/clients/new.html.erb
<div id="main-container" class="container">
  <div class="row">
    <div id="sidebar" class="col-xs-3">
      <!-- sidebar content -->
    </div>
      <div id="content" class="col-xs-9">
        
        <%= form_for @client do |f| %> 
          <p>
            <%= f.email_field :email, placeholder: 'Email', required: true %></br>
            <%= f.text_field :firstname, placeholder: 'First Name', required: true %></br>
            <%= f.text_field :lastname, placeholder: 'Last Name', required: true %>
            
              <br />
            <%= f.password_field :password, placeholder: 'Password', required: true %></br>
   
            <%= f.submit "Signup!" %>
          </p>
 
          <% end %>
        </div>
    </div>
</div> 

project2/app/views/clients/show.html.erb
<div class="profile container">
  <div class="row">
    <div class="col-md-8 col-xs-10">
      <div class="well panel panel-default">
        <div class="panel-body">
          <div class="row">
            <div class="col-xs-12 col-sm-4 text-center">
              <img src="http://placekitten.com.s3.amazonaws.com/homepage-samples/408/287.jpg" alt="" class="center-block img-circle img-thumbnail img-responsive">
            </div>
            <h1>Welcome, <%= @client.firstname %></h1>
            <p>
            <p><strong></p>About:</strong> Client information,Proin vitae convallis libero. Pellentesque vel metus vel orci feugiat fringilla nec sed tellus. Nam id porttitor turpis, eget auctor magna. Aenean consectetur blandit tortor, vel suscipit nisl. 
          </p>

            <p><strong>Member since: </strong><%= @client.created_at %></p>
            <p><strong></p>Nam id porttitor turpis</strong>
            <span class="label label-info tags">here</span>
          </p>
        </div>
        <!-- col -->
        <div class="clearfix"></div>
          <div class="col-xs-12 col-sm-4">
            
            
            <p><small> <%= @client.favorites %></small></p>
          </div>
        <!-- col -->
            <div class-"col-xs-12 col-sm-4">
              <h3><strong>43</strong></h3>
              <p><small>Favorites</small></p>
            </div>
            <h3><strong>Performers you've contacted: </strong></h>
            <!--/col-->
            <div class="col-xs-12 col-sm-4">
            <button type="button" class="btn btn-warning"><%= link_to "Logout", logout_path, method: :delete %></button>
            <button type="button" class="btn btn-warning"><%= link_to "Edit", edit_client_path, method: :get %></button>

            </div>
            <!--/col-->
          </div>
          <!--/row-->
        </div>
        <!--/panel-body-->
      </div>
      <!--/panel-->
    </div>
    <!--/col--> 
  </div>
  <!--/row--> 
</div>
<!--/container-->

project2/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Project2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'partials/navbar' %>



<% flash.each do |key, value| %>
        <div class="alert alert-<%= key %> alert-dismissible">

          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <%= value %></div>
      <% end %>

<%= yield %>

</body>
</html>

project2/app/views/partials/_navbar.html.erb
<nav class="navbar navbar-default navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <%= link_to "Project 2", "/", :"data-no-turbolink" => true, class: "navbar-brand" %>  
      <!-- <a class="navbar-brand" href="/"></a> -->


    </div>
    <!-- @user.present? -->
    <% if current_client %>

      <%= button_to "Logout", logout_path, method: "delete", class: "btn btn-default navbar-right navbar-btn" %>
      <%= button_to "Profile", client_path, method: "get", class: "btn btn-default navbar-right navbar-btn" %>

    <% else %>
     <span> <%= button_to "Login", "/sessions/new", method: "get", class: "red btn btn-default navbar-right navbar-btn" %></span> 

      <span><%= button_to "Sign Up", "/clients/new", method: "get", class: "btn btn-default navbar-right navbar-btn" %></span>
    <% end %>
  </div><!-- /.container-fluid -->
</nav>

project2/app/views/performer_sessions/create.html.erb
<h1>PerformerSessions#create</h1>
<p>Find me in app/views/performer_sessions/create.html.erb</p>

project2/app/views/performer_sessions/destroy.html.erb
<h1>PerformerSessions#destroy</h1>
<p>Find me in app/views/performer_sessions/destroy.html.erb</p>

project2/app/views/performer_sessions/new.html.erb
<h1>Performer Log In</h1>

<%= form_for @performer, url: "/performer_sessions", method: "post" do |f| %>
	<div>
		<%= f.text_field :email, placeholder: "Email", required: true %>
	</div>
	<div>
		<%= f.password_field :password, placeholder: "Password", required: true %>
	</div>
	<div>
		<%= f.submit "Log In" %>
	</div>
<% end %>

project2/app/views/performers/edit.html.erb
<h1>Edit Performer Profile</h1>


<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In non posuere nisi. Vivamus ut ipsum dolor. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Fusce tortor odio, mattis in nunc non, ornare varius enim. Aenean ultricies ante suscipit eros scelerisque, nec rhoncus sem tempor.</p>

<%= form_for @performer do |f| %>
	<div>
		<%= f.text_field :performer_name, placeholder: "Your name or group name", required: true %>
	</div>
	<div>
		<%= f.email_field :email, placeholder: "Your email address", required: true %>
	</div>
	<div>
		<%= f.password_field :password, placeholder: "Password", required: true %>
	</div>
	<div>
		<%= f.text_field :city, placeholder: "Where are you?", required: true %>
	</div>
	<div>
		<!-- I've put some this information in the seeds.rb file as well - HS -->
		<%= f.select :category_id, [['Musical Act', 1], ['Comedy Act', 2], ['Circus Act', 3]], required: true, class: "dropdown-menu" %>
	</div>
	<div>
		<%= f.text_field :performer_subcategory, placeholder: "Your act type", required: true %>
	</div>
	<div>
		<%= f.select :hourly_rate, [['$1-25 per hour', '$1-25 per hour'], ['$26-50 per hour', '$26-50 per hour'], ['$51-75 per hour', '$51-75 per hour'], ['$76-100 per hour', '$76-100 per hour'], ['$101-150 per hour', '$101-150 per hour']], required: true %>
	</div>
	<div>
		<%= f.text_area :description, placeholder: "Describe your act for us! Max 500 characters.", required: true, cols: 50, rows: 6 %>
	</div>
	<div>
		<%= f.submit "Sign Up" %>
	</div>
<% end %>

project2/app/views/performers/index.html.erb
<div class="container">
	<h1>View All Performers</h1>
	<div>
		<select name="category_id" id="category_id">
			 <option value="1">Musical Acts</option>
			 <option value="2">Comedy Acts</option>
			 <option value="3">Circus Acts</option>
		</select>
	</div>

	<% @performers.each do |performer| %>

		<div>
			<h2> <%= performer.performer_name %></h2>

			<p>
			City: <%= performer.city %>
			<br>
			Category: <%= performer.category_id %>
			<br>
			Subcategory: <%= performer.performer_subcategory %>
			<br>
			Price: <%= performer.hourly_rate %>
			<br>
			Description: <%= performer.description %></p>
		</div>

	<% end %>
</div>

project2/app/views/performers/new.html.erb
<h1>Ready to get out there and make some $$$?</h1>
<h2>Sign up now!</h2>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In non posuere nisi. Vivamus ut ipsum dolor. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Fusce tortor odio, mattis in nunc non, ornare varius enim. Aenean ultricies ante suscipit eros scelerisque, nec rhoncus sem tempor.</p>

<%= form_for @performer do |f| %>
	<div>
		<%= f.text_field :performer_name, placeholder: "Your name or group name", required: true %>
	</div>
	<div>
		<%= f.email_field :email, placeholder: "Your email address", required: true %>
	</div>
	<div>
		<%= f.password_field :password, placeholder: "Password", required: true %>
	</div>
	<div>
		<%= f.text_field :city, placeholder: "Where are you?", required: true %>
	</div>
	<div>
		<!-- I've put some this information in the seeds.rb file as well - HS -->
		<%= f.select :category_id, [['Musical Act', 1], ['Comedy Act', 2], ['Circus Act', 3]], required: true, class: "dropdown-menu" %>
	</div>
	<div>
		<%= f.text_field :performer_subcategory, placeholder: "Your act type", required: true %>
	</div>
	<div>
		<%= f.select :hourly_rate, [['$1-25 per hour', '$1-25 per hour'], ['$26-50 per hour', '$26-50 per hour'], ['$51-75 per hour', '$51-75 per hour'], ['$76-100 per hour', '$76-100 per hour'], ['$101-150 per hour', '$101-150 per hour']], required: true %>
	</div>
	<div>
		<%= f.text_area :description, placeholder: "Describe your act for us! Min. 30, max. 500 characters.", required: true, cols: 50, rows: 6 %>
	</div>
	<div>
		<%= f.file_field :avatar, class: "form-control title_input_field2" %>
	</div>
	<div>
		<%= f.file_field :image1, class: "form-control title_input_field2" %>
	</div>
	<div>
		<%= f.file_field :image2, class: "form-control title_input_field2" %>
	</div>
	<div>
		<%= f.file_field :image3, class: "form-control title_input_field2" %>
	</div>

	<div>
		<%= f.text_field :video1, placeholder: "Enter a URL link from YouTube" %>
	</div>

	<div>
		<%= f.text_field :video2, placeholder: "Enter a URL link from YouTube" %>
	</div>

	<div>
		<%= f.text_field :video3, placeholder: "Enter a URL link from YouTube" %>
	</div>

	<div>
		<%= f.submit "Sign Up" %>
	</div>
<% end %>

project2/app/views/performers/show.html.erb
<div class="container">

	<%= link_to "Log Out", "/performer_sessions", method: :delete %><br>

	<%= link_to "Edit Profile", edit_performer_path, method: :get %>

	<div>
		<strong>Email:</strong> <%= @performer.email %>
	</div>






	<div>
		<%= image_tag @performer.avatar.url(:thumb), :class => "img-circle" %>
	</div>
	<div>
		<h1><%= @performer.performer_name %></h1>
		<h3><%= @performer.city %></h3>
		<strong>Category:</strong> <%= @category.category %> - <%= @performer.performer_subcategory %>
		<br>
		<strong>Hourly Rate:</strong> <%= @performer.hourly_rate %>
	</div>

	<div>
		<strong>Description:</strong> <%= @performer.description %>
	</div>
	<br>

<div id="performer-img" class="carousel slide" data-ride="carousel">
 <!-- Indicators -->
 <ol class="carousel-indicators">
   <li data-target="#performer-img" data-slide-to="0" class="active"></li>
   <li data-target="#performer-img" data-slide-to="1"></li>
   <li data-target="#performer-img" data-slide-to="2"></li>
   <li data-target="#performer-img" data-slide-to="3"></li>
 </ol>

 <!-- Wrapper for slides -->
 <div class="carousel-inner" role="listbox">
   <div class="item active">
     <img src="<%= @performer.image1 %>">
   </div>

   <div class="item">
     <img src="<%= @performer.image2 %>">
   </div>

   <div class="item">
     <img src="<%= @performer.image3 %>">
   </div>

 </div>

 <!-- Left and right controls -->
 <a class="left carousel-control" href="#performer-img" role="button" data-slide="prev">
   <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
   <span class="sr-only">Previous</span>
 </a>
 <a class="right carousel-control" href="#performer-img" role="button" data-slide="next">
   <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
   <span class="sr-only">Next</span>
 </a>
</div>

 <br><br>

<div id="performer-vid" class="carousel slide" data-ride="carousel">
 <!-- Indicators -->
 <ol class="carousel-indicators">
   <li data-target="#performer-vid" data-slide-to="0" class="active"></li>
   <li data-target="#performer-vid" data-slide-to="1"></li>
   <li data-target="#performer-vid" data-slide-to="2"></li>
   <li data-target="#performer-vid" data-slide-to="3"></li>
 </ol>

 <!-- Wrapper for slides -->
 <div class="carousel-inner" role="listbox">
   <div class="item embed-container active">
      <%= embed(@performer.video1) %>
   </div>

   <div class="item embed-container">
      <%= embed(@performer.video2) %>
   </div>

   <div class="item embed-container">
     <%= embed(@performer.video3) %>
   </div>
 </div>

 <!-- Left and right controls -->
 <a class="left carousel-control" href="#performer-vid" role="button" data-slide="prev">
   <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
   <span class="sr-only">Previous</span>
 </a>
 <a class="right carousel-control" href="#performer-vid" role="button" data-slide="next">
   <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
   <span class="sr-only">Next</span>
 </a>
</div>

	
	</div>